# Generated by Django 5.1.6 on 2026-01-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
